run:
  type: Full_finetune_MOE_bind
  pretrained_ckpt: checkpoints/demo/deepseek_pretrain/demo_deepseek_pretrain.pt
  mod_pretrained_with_MTP: false

model:
  vocab_size: 31
  block_size: 256
  n_layer: 2
  n_head: 4
  n_embd: 128

  kv_lora_rank: 32
  q_lora_rank: 32
  rope_dim: 16
  bias: true

  mtp_num_heads: 0
  dropout: 0.1

  n_experts: 4
  n_experts_per_token: 2
  expert_intermediate_size: 128
  shared_expert_intermediate_size: 128
  use_shared_expert: true

  mtp_loss_weight: 0.0
  aux_loss_weight: 0.1

data:
  name: demo_finetune
  dtype: uint16
  preprocessed_train: data/demo/tokenized_ft/demo_ft_train
  preprocessed_val: data/demo/tokenized_ft/demo_ft_val

training:
  learning_rate: 0.0001
  min_lr: 0.00001
  max_iters: 50
  warmup_steps: 5
  eval_iters: 25
  batch_size: 4
  gradient_accumulation_steps: 1
  checkpoint_dir: checkpoints/demo/deepseek_finetune
  out_mod_name: "demo_deepseek_finetune"
  conditional_masking: true

logging:
  project: moebind_demo
  seed: 42
  id: demo_deepseek_finetune

# Run:
# python -m scripts.train --config configs/finetune/demo/deepseek.yaml
