run:
  type: Full_finetune_LLAMA2
  pretrained_ckpt: checkpoints/demo/llama2_pretrain/demo_llama2_pretrain.pt
  mod_pretrained_with_MTP: false

model:
  vocab_size: 31
  block_size: 256
  n_layer: 2
  n_head: 4
  n_embd: 128
  n_kv_heads: 2
  multiple_of: 32
  ffn_dim_multiplier: null
  norm_eps: 0.00001
  dropout: 0.1

data:
  name: demo_finetune
  dtype: uint16
  preprocessed_train: data/demo/tokenized_ft/demo_ft_train
  preprocessed_val: data/demo/tokenized_ft/demo_ft_val

training:
  learning_rate: 0.0001
  min_lr: 0.00001
  max_iters: 50
  warmup_steps: 5
  eval_iters: 25
  batch_size: 4
  gradient_accumulation_steps: 1
  checkpoint_dir: checkpoints/demo/llama2_finetune
  out_mod_name: "demo_llama2_finetune"
  conditional_masking: true

logging:
  project: moebind_demo
  seed: 42
  id: demo_llama2_finetune

# Run:
# python -m scripts.train --config configs/finetune/demo/llama2.yaml
